name: Deploy PROD

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy 'main' branch to Digital Ocean Droplet
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} '
          cd /var/www/rokis-corner/prod \
          && eval "$(ssh-agent -s)" \
          && ssh-add ~/.ssh/github_ed25519 \
          && git checkout main \
          && git pull \
          && docker build -t rokis-corner-node-prod . \
          && docker run --rm -v $(pwd)/build:/app/build rokis-corner-node-prod
          '
